[package]
name = "transform"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
regex = "1.12.2"
rayon = "1.11.0"

[dev-dependencies]
rstest = "0.26.1"
